name: Main
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install dependencies
              run: yarn install
            - name: Run test
              run: yarn test
              env:
                  TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
                  EXCHANGE_TOKEN: ${{secrets.EXCHANGE_TOKEN}}
                  NODE_ENV: ${{secrets.NODE_ENV}}
                  DB_HOST: ${{secrets.DB_HOST}}
                  DB_NAME: ${{secrets.DB_NAME}}
                  DB_USER: ${{secrets.DB_USER}}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    deploy:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "stin-bot"
                  heroku_email: "nikita.tashilin@gmail.com"