name: Main
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - name: Install dependencies
              run: npm install
            - name: Run test
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: [ build ]
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "stin-bot"
                  heroku_email: "nikita.tashilin@gmail.com"
              env:
                  NODE_ENV: "production"
                  env_file: /.env